### ISSUE TITLE
/maids/0/appids does not return a 400 when numOfIds exceeds the max value

### ISSUE THREAD

**Issue by CMaylone** [smartdevicelink/sdl_shaid_maids#2]
When posting a numOfIds that exceeds the max value at /maids/0/appids, it returns a `500` status code instead of the expected `400` status code.

Steps to reproduce:

`POST /maids/0/appids` with the body:

```JSON
{
  "numOfIds":100000000
}
```

**Comment by ssmereka** [comment]
Fixed issue in riposte.
